### ISSUE TITLE
Weird cast

### ISSUE THREAD

**Issue by derzhavin3016** [yuphia/processor#10]
https://github.com/yuphia/processor/blob/2416af18d516e66e6787a07c1376a02231dadb9b/assembler/assembler.h#L75
For what purpose did you cast opcode to `double`?

**Comment by derzhavin3016** [comment]
And why did you use `fprintf`? Is it possible to store data in some buffer and then put it to file instead? Because I think it's better not having opened file during all your program

**Comment by yuphia** [comment]
Resolved due to refactored compilation methods, check later commits

**Comment by yuphia** [comment]
resolved here: e293a5080f900897e79056e205b0d655052d110d
