### ISSUE TITLE
Weird line

### ISSUE THREAD

**Issue by derzhavin3016** [yuphia/processor#15]
https://github.com/yuphia/processor/blob/cb95f8e4a405c9de748a9ed4af87dedab66a8dfa/assembler/assembler.cpp#L6
What you do here?

**Comment by yuphia** [comment]
Erase everything what was written in the file

**Comment by derzhavin3016** [comment]
If you call `open()` with `w` argument, file will be erased automatically

**Comment by yuphia** [comment]
partially resolved here 673f7c76b7e83627407a0394fdd2fe95990b8507

**Comment by yuphia** [comment]
actually it was fully resolved there
