### ISSUE TITLE
Struct

### ISSUE THREAD

**Issue by Tako-San** [yuphia/processor#22]
https://github.com/yuphia/processor/blob/bec5e225a765554ede7bc4f4ddcbb05c67d5b116/assembler/assembler.cpp#L18

It is not necessary to write `struct` every time if you are using `C++` compiler. Even if you are using `C` compiler you may use typedef to avoid writing `struct`.

**Comment by yuphia** [comment]
I was told that but decided to still use it this way in order to have the same codestyle in the whole project (all files in lib and assembler and disassembler). Will change in future projects.

**Comment by Tako-San** [comment]
> I was told that but decided to still use it this way in order to have the same codestyle in the whole project (all files in lib and assembler and disassembler). Will change in future projects.

Okay, you may close issue than
