### ISSUE TITLE
Unsafe behaviour

### ISSUE THREAD

**Issue by derzhavin3016** [yuphia/processor#9]
https://github.com/yuphia/processor/blob/2416af18d516e66e6787a07c1376a02231dadb9b/assembler/assembler.h#L75-L77
It's too weird to check the validity of `arg` only after printing to file

**Comment by yuphia** [comment]
Resolved due to refactored compilation methods, check later commits

**Comment by yuphia** [comment]
Resolved here: e293a5080f900897e79056e205b0d655052d110d
